Build/Deploy/Samples/AspNetMvcRazorCs/Controllers/SqlServerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Krystalware.SlickUpload;
using AspNetMvcRazorCs.Models;

namespace AspNetMvcRazorCs.Controllers
{
    public class SqlServerController : Controller
    {
        
        public ActionResult Index(SqlServerModel model)
        {
            if (model == null)
                model = new SqlServerModel();

            
    try
    {
        model.ExistingFiles = new AspNetMvcRazorCs.Storage.SqlFileRepository("sqlServer").GetAll();
    }
    catch (Exception ex)
    {
        model.Exception = ex;
    }


            return View(model);
        }

        public ActionResult UploadResult(SqlServerModel model, UploadSession session)
        {
            

            model.UploadSession = session;

            return View(model);
        }
        

        
        public ActionResult Download(int id)
        {
            AspNetMvcRazorCs.Storage.SqlFileRepository repository = new AspNetMvcRazorCs.Storage.SqlFileRepository("sqlServer");
            AspNetMvcRazorCs.Storage.SqlFile file = repository.GetById(id);

            return File(repository.GetDataStream(file), "application/octet-stream", file.Name);
        }

    }
}

Build/Deploy/Samples/AspNetMvcRazorCs/Views/SqlServer/Index.cshtml
        @model AspNetMvcRazorCs.Models.SqlServerModel
    @using Krystalware.SlickUpload;
@using Krystalware.SlickUpload.Web;
@using Krystalware.SlickUpload.Web.Mvc;

@{
    Layout = "~/Views/Shared/_Layout.cshtml";
    ViewBag.Title = "Sql Server";
}


@section head
            {
    <script type="text/javascript">
        
        function startUpload()
        {
            var slickUpload = kw("slickUpload");

            if (slickUpload)
                slickUpload.start();
        }
        
        
        function cancelUpload()
        {
            kw("slickUpload").cancel();

            document.getElementById("cancelButton").style.display = "none";
        }

        
        function onFileSelectionChanged(data)
        {
            document.getElementById("uploadButton").className = "button" + (kw("slickUpload").get_Files().length > 0 ? "" : " disabled");
        }
        

        function onSessionStarted(data)
        {
            
            document.getElementById("uploadButton").style.display = "none";

            document.getElementById("cancelButton").style.display = "block";
        }
        
        function onBeforeSessionEnd(data)
        {
            document.getElementById("uploadButton").style.display = "none";
            document.getElementById("cancelButton").style.display = "none";
        }
        

        
    </script>
            }


    @using (Html.BeginForm("UploadResult", "SqlServer", FormMethod.Post, new { id = "uploadForm", enctype = "multipart/form-data" })) {
        
        <div id="uploadPanel">
            
            <table class="settings">
                <tbody>
                    <tr>
                        <th style="font-weight:bold;border-bottom:solid 1px #ccc">Select files to upload</th>
                    </tr>
                    <tr>
                        <td>
                            

                            @Html.KrystalwareRazor(new SlickUpload() { 
Id = "slickUpload",
OnClientUploadSessionStarted = "onSessionStarted",
OnClientBeforeSessionEnd = "onBeforeSessionEnd",
OnClientFileAdded = "onFileSelectionChanged",
OnClientFileRemoved = "onFileSelectionChanged",
SelectorTemplate = new Template(@<text>
                               
                                    <a class="button">
                                        <span><b class="icon add"></b> Add files</span>
                                    </a>
                                    
</text>),
ShowDropZoneOnDocumentDragOver = true,
HtmlAttributes = new { @class = "simple", Style = "overflow:hidden;zoom:1"},
FileSelectorHtmlAttributes = new { Style = "float:left"},
FileListHtmlAttributes = new { Style = "clear:both"},
UploadProgressDisplayHtmlAttributes = new { Style = "clear:both"},
UploadProfile = "sqlServer",
AutoUploadOnSubmit = true,
UploadFormId = "uploadForm",
SelectorFolderTemplate = new Template(@<text>
                               
                                    <a class="button">
                                        <span><b class="icon add-folder"></b> Add folder</span>
                                    </a>
                                    
</text>),
SelectorDropZoneTemplate = new Template(@<text>
                               
                                    <div>Drag and drop files here.</div>                
                                    
</text>),
FileItemTemplate = new Template(@<text>
                               
                                    <div class="filedata">
                                        @Html.KrystalwareRazor(new FileListElement() { Element = FileListElementType.FileName } )
                                        &ndash;
                                        @Html.KrystalwareRazor(new FileListElement() { Element = FileListElementType.FileSize, Template = new Template("(calculating)") } )
                                    </div>
                                        @Html.KrystalwareRazor(new FileListRemoveCommand() { HtmlAttributes = new { href = "javascript:;"}, Template = new Template("[x]") } )
                                        @Html.KrystalwareRazor(new FileListElement() { Element = FileListElementType.ValidationMessage, HtmlAttributes = new { style = "color:#f00"} } )
                                    
</text>),
ProgressTemplate = new Template(@<text>
                               
                                        <div id="duringUpload">
                                            <div>
                                                Uploading @Html.KrystalwareRazor(new UploadProgressElement() { Element = UploadProgressElementType.FileCount } ) file(s),
                                                @Html.KrystalwareRazor(new UploadProgressElement() { Element = UploadProgressElementType.ContentLengthText, Template = new Template("(calculating)") } ).
                                            </div>
                                            <div>
                                                Currently uploading: @Html.KrystalwareRazor(new UploadProgressElement() { Element = UploadProgressElementType.CurrentFileName } )
                                                file @Html.KrystalwareRazor(new UploadProgressElement() { Element = UploadProgressElementType.CurrentFileIndex } )
                                                of @Html.KrystalwareRazor(new UploadProgressElement() { Element = UploadProgressElementType.FileCount } ).
                                            </div>
                                            <div>
                                                Speed: @Html.KrystalwareRazor(new UploadProgressElement() { Element = UploadProgressElementType.SpeedText, Template = new Template("(calculating)") } )
                                            </div>
                                            <div>
                                                @Html.KrystalwareRazor(new UploadProgressElement() { Element = UploadProgressElementType.TimeRemainingText, Template = new Template("(calculating)") } )
                                            </div>
                                            <div class="progressBarContainer">
                                                @Html.KrystalwareRazor(new UploadProgressBar())
                                                <div class="progressBarText">
                                                    @Html.KrystalwareRazor(new UploadProgressElement() { Element = UploadProgressElementType.PercentCompleteText, Template = new Template("(calculating)") } )
                                                </div>
                                            </div>
                                        </div>
                                    
</text>)
 } )
@Html.KrystalwareRazor(new KrystalwareScriptRenderer())                            
                        </td>
                    </tr>
                </tbody>
            </table>
            <p>
                        <a id="uploadButton" href="javascript:;" onclick="startUpload()" class="button disabled" >
 <span><b class="icon upload"></b> Upload Files</span>        </a>

                <a id="cancelButton" href="javascript:;" onclick="cancelUpload()" style="display:none" class="button">
                    <span><b class="icon cancel"></b> Cancel</span>
                </a>
                <div style="clear:both"></div>
            </p>
        </div>
    }
    
@if (Model.Exception == null) {if (Model.ExistingFiles.Count > 0) {        <h2>Existing Files</h2>
        <table class="results" width="99%" cellpadding="4" cellspacing="0">
            <thead>
                <th align="left">Name</th>
                <th align="left">Length (bytes)</th>
            </thead>
            <tbody>
            @foreach (AspNetMvcRazorCs.Storage.SqlFile file in Model.ExistingFiles) {
                <tr>
                    <td>                        
                        @(Html.ActionLink(file.Name, "Download", new { id = file.Id }, new { target="_blank" }))
                    </td>
                    <td>
                        @file.Length
                    </td>
                </tr>
            }
            </tbody>
        </table>
        <br />
}} else {    <div style="border:1px solid #c00;padding:.5em;margin-bottom:1em;">
        <b style="color:#f00">ERROR:</b> Could not connect to database. Please ensure the connection string and table information in the web.config are correct and that the file table has been properly created. Exception:<br /> <br />@Model.Exception.GetType().FullName: @Model.Exception.Message
    </div>
}

@section configuration
            {    <h2>Configuration</h2>
<p>Configuration for the SQL sample involves creating the file database and table and configuring SlickUpload
   to point at that database. To prepare the database, perform the following steps:</p>
<ol>
    <li>Create a new database, or select an existing database to use</li>
    <li>Change the su connection string in the &lt;connectionStrings&gt; web.config section to point to the database selected above</li>
</ol>
<p>SlickUpload supports writing to one of 3 file column data types: IMAGE, VARBINARY(MAX), and FILESTREAM. Each has different configuration steps:</p>
<h3>IMAGE</h3>
<ol>
    <li>Open the SqlFileTable-IMAGE.sql script in the SlickUpload distribution package root folder and run it on the database created above</li>
    <li>Open the web.config, locate the uploadProfile named "sqlServer", and change the dataType attribute to "IMAGE"</li>
</ol>
<h3>VARBINARY(MAX)</h3>
<ol>
    <li>Open the SqlFileTable-VARBINARYMAX.sql script in the SlickUpload distribution package root folder and run it on the database created above</li>
    <li>Open the web.config, locate the uploadProfile named "sqlServer", and change the dataType attribute to "VarBinaryMax"</li>
</ol>
<h3>FILESTREAM</h3>
<ol>
    <li>Modify the su connection string in the &lt;connectionStrings&gt; web.config section to use integrated security</li>
    <li>Ensure the database selected above has been enabled for FILESTREAM access. For more information, see <a href="http://msdn.microsoft.com/en-us/library/cc645585.aspx">How to: Create a FILESTREAM-Enabled Database</a></li>
    <li>Open the SqlFileTable-FILESTREAM.sql script in the SlickUpload distribution package root folder and run it on the database created above. Make sure to update the script based on the name of the FILESTREAM FileGroup you have created.</li>
    <li>Open the web.config, locate the uploadProfile named "sqlServer", and change the dataType attribute to "FileStream"</li>
</ol>
            }
@section description
            {
    Upload directly to a SQL Server IMAGE, VARBINARY(MAX), or FILESTREAM field, streaming the file to the field with minimal memory usage.
            }

Build/Deploy/Samples/AspNetMvcRazorCs/Views/SqlServer/UploadResult.cshtml
        @model AspNetMvcRazorCs.Models.SqlServerModel
    @using Krystalware.SlickUpload;
@using Krystalware.SlickUpload.Web;
@using Krystalware.SlickUpload.Web.Mvc;

@{
    Layout = "~/Views/Shared/_Layout.cshtml";
    ViewBag.Title = "Sql Server";
}

            <h2>Upload Result</h2>
             @if (Model.UploadSession != null) {
                <p>Result: @Model.UploadSession.State.ToString()</p>
                if (Model.UploadSession.State != UploadState.Error) {
                <p>Files Uploaded: @Model.UploadSession.UploadedFiles.Count.ToString()</p>
                <table class="results" width="99%" cellpadding="4" cellspacing="0">
                    <thead>
                        <tr>
                            <th align="left">Server Location</th>
                            <th align="left">Mime Type</th>
                            
                            <th align="left">Length (bytes)</th>
                        </tr>
                    </thead>
                    <tbody>
@foreach (UploadedFile file in Model.UploadSession.UploadedFiles) {                        <tr>
                            <td>
                                @Html.Raw(file.ServerLocation.Replace("\\", "\\<wbr />"))
                            </td>
                            <td>
                                @file.ContentType
                            </td>
                            
                            <td>
                                @file.ContentLength
                            </td>
                        </tr>
}                        @if (Model.UploadSession.UploadedFiles.Count == 0) {
                        <tr class="nodata">
                            <td colspan="3">No files recieved.</td>
                        </tr>
                        }
                    </tbody>
                </table>
                } else {
                <p>Error Summary: @Model.UploadSession.ErrorSummary</p>
                }
            } else {
            <p>No upload recieved.</p>
            }
            <p>
        <a id="newUploadButton"  href="@Url.Action("Index")" class="button" >
 <span><b class="icon newupload"></b> New Upload</span>        </a>
                <div style="clear:both"></div>
            </p>
@section description
            {Upload directly to a SQL Server IMAGE, VARBINARY(MAX), or FILESTREAM field, streaming the file to the field with minimal memory usage.            }
                          